apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/lovetcs-org/AutomatedAWSPlatformFoundation.git
    targetRevision: main
    path: helm/my-app
    helm:
      valueFiles:
        - values-dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true